### ISSUE TITLE
Java example for OpenID config

### ISSUE THREAD

**Issue by vdobrikov** [micronaut-projects/micronaut-oauth2#1]
Please add Java example how to add OpenID config. I saw there is a Groovy one, but unfortunately I'm not that familiar with it. I think the same for many others.

**Comment by TeNNoX** [comment]
I actually needed only the following yml config:
```yaml
micronaut:
  security:
    enabled: true
    oauth2:
      client-id: 'service'
      client-secret: 'abcd0ad-4c72-4e78-aeba-d0b25faf536d'
      openid-configuration: 'https://keycloak.domain.com/auth/realms/master/.well-known/openid-configuration'
    token:
      jwt:
        enabled: true
```

No Java config required.

**Comment by mikaelhg** [comment]
My working KeyCloak configuration:

```yaml
  security:
    enabled: true
    oauth2:
      client-id: '****'
      client-secret: '****'
      issuer: https://keycloak.server/auth/realms/master
    session:
      enabled: true
    token:
      jwt:
        enabled: true
        cookie:
          enabled: true
```
