### ISSUE TITLE
Resource access based roles with @Secured annotation

### ISSUE THREAD

**Issue by TeNNoX** [micronaut-projects/micronaut-oauth2#7]
Hello, I'm trying to get a micronaut microservice working with OpenID Connect.
I managed to get the basic setup working eventually (with help of **micronaut-oauth2**).

But when trying to set up role-based authentication via `@Secured`, I noticed that the default [`SecuredAnnotationRule`](https://github.com/micronaut-projects/micronaut-core/blob/master/security/src/main/java/io/micronaut/security/rules/SecuredAnnotationRule.java) cannot parse roles from the JWT generated by Keycloak. It is able to get list of roles from an Iterable, but the format is:
```json
{
  "realm_access": {
    "roles": [
      "global_role_1"
    ]
  },
  "resource_access": {
    "resource_1": {
      "roles": [
        "resource_specific_role_1"
      ]
    }
  }
}
```

Unfortunately, I cannot (simply) extend the `SecuredAnnotationRule` nor the the `AbstractSecurityRule` as their constructors are package-private.

Do you plan to support resource-based authorization?

Should I create an issue for this in *micronaut-core*?

**Comment by TeNNoX** [comment]
Originally asked [on gitter](https://gitter.im/micronautfw/questions?at=5c6438405095f6660ce986e6)

**Comment by TeNNoX** [comment]
If you want I can send you the code of the custom `ResourceBasedSecuredAnnotationRule` that I implemented now as a workaround.

**Comment by graemerocher** [comment]
Would be useful thanks. Hopefully @sdelamo or @jameskleeh can take a look soon

**Comment by TeNNoX** [comment]
Here's my implementation.
As mentioned, it could be greatly simplified if `SecuredAnnotationRule` would have a public constructor.

It can be enabled with this config: (see the last two lines)
```yaml
micronaut:
  security:
    enabled: true
    oauth2:
      client-id: 'service-name'
      client-secret: 'abcdb0ad-4c72-4e78-aeba-d0b25faf536d'
      openid-configuration: 'https://keycloak.domain.com/auth/realms/platform/.well-known/openid-configuration'
    token:
      jwt:
        enabled: true
      resource-based:
        enabled: true
        resource-name: 'service-name'
```
[ResourceBasedSecuredAnnotationRule.zip](https://github.com/micronaut-projects/micronaut-oauth2/files/2861292/ResourceBasedSecuredAnnotationRule.zip)
